name: Setup terraform environment
description: Checkout and configure the CI environment for terraform

inputs:
  branch:
    description: 'The branch to checkout'
    required: false

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ vars.AWS_ARN }}

    - name: Add environment variables
      shell: bash
      run: |-
        echo "${{ secrets.INFRASTRUCTURE_TFVARS }}" | base64 -d > infrastructure/.tfvars
        echo "${{ secrets.APPLICATIONS_TFVARS }}" | base64 -d > applications/.tfvars

