apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: global
  source:
    repoURL: 'https://github.com/presentium/infrastructure'
    targetRevision: production
    path: kubernetes/core/authentik
  destination:
    name: in-cluster
    namespace: core-authentik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
