apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: global
  source:
    repoURL: 'https://github.com/presentium/infrastructure'
    targetRevision: production
    path: kubernetes/system/argocd
  destination:
    name: in-cluster
    namespace: argocd
