apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: authentik-

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: redis-authentik

components:
  - ../../../templates/redis
