apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: global
  namespace: argocd
spec:
  sourceRepos:
    - '!https://github.com/presentium/api'
    - https://github.com/presentium/infrastructure
  sourceNamespaces:
    - 'system'
    - 'core'
  destinations:
    - namespace: 'system-*'
      server: '*'
    - namespace: 'core-*'
      server: '*'
    - namespace: 'argocd'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
