apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: presentium-staging
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/presentium/infrastructure
    - https://github.com/presentium/api
  sourceNamespaces:
    - 'apps'
  destinations:
    - namespace: '*'
      server: 'staging-*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
