apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels: { }
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: redis
      containers:
        - name: redis
          image: redis
          imagePullPolicy: Always
          args: [ '--save', '', '--appendonly', 'no' ]
          ports:
            - name: tcp-redis
              containerPort: 6379
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
