apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redis
subjects:
  - kind: ServiceAccount
    name: redis
