apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # exec in containers
  exec.enabled: 'true'
  admin.enabled: 'true'
  # kustomize requirements
  kustomize.buildOptions: '--enable-helm --load-restrictor LoadRestrictionsNone'
  application.resourceTrackingMethod: 'annotation+label'
  application.instanceLabelKey: 'argocd.argoproj.io/instance'
  # Set app resync to a shorter value (default 180s)
  timeout.reconciliation: '60s'
