apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/presentium/infrastructure'
    targetRevision: production
    path: kubernetes/_applications/core
  destination:
    name: in-cluster
    namespace: core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
