apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/presentium/infrastructure'
    targetRevision: production
    path: kubernetes/_applications/apps
  destination:
    name: in-cluster
    namespace: apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
