name: Check for infrastructure drift

on:
  schedule:
    - cron:  "0 8 * * *"

permissions:
  id-token: write
  contents: read

jobs:
  check_drift:
    runs-on: ubuntu-latest
    name: Check for drift of terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ARN }}
          role-session-name: terraform-check

      - name: Check for drift
        uses: dflook/terraform-check@v1
        with:
          path: terraform