name: Check for infrastructure drift

on:
  schedule:
    - cron: "0 8 * * *"

permissions:
  id-token: write
  contents: read

jobs:
  check_drift:
    runs-on: ubuntu-latest
    name: Check for drift of terraform configuration

    strategy:
      fail-fast: false
      matrix:
        branch: [ production ]
        context: [ infrastructure, applications ]

    steps:
      - name: Setup env
        uses: ./.github/actions/setup
        with:
          branch: ${{ matrix.branch }}

      - name: Check for drift
        uses: dflook/terraform-check@v1
        with:
          path: ${{ matrix.context }}
