name: Create terraform plan

on: [ pull_request ]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a plan for the terraform configuration

    strategy:
      fail-fast: false
      matrix:
        context: [ infrastructure, applications ]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |-
            context:
              - '${{ matrix.context }}/**'

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        if: steps.changes.outputs.context == 'true'
        with:
          path: ${{ matrix.context }}
