name: Apply terraform plan

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply the terraform plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ARN }}
          role-session-name: terraform-apply

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform