name: Apply terraform plan

on:
  push:
    branches:
      - production
    paths:
      - 'infrastructure/**'

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply the terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: infrastructure
