name: Apply applications configuration

on: [ workflow_dispatch ]

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply the terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         ref: production

      - name: Setup env
        uses: ./.github/actions/setup

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: applications
          auto_approve: true
