name: Validate changes

on:
  push:
    branches-ignore:
      - production

permissions:
  contents: read
  id-token: write

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of terraform files

    strategy:
      matrix:
        context: [ infrastructure, applications ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ARN }}

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ${{ matrix.context }}

  validate:
    runs-on: ubuntu-latest
    name: Validate terraform configuration

    strategy:
      matrix:
        context: [ infrastructure, applications ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ARN }}

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: ${{ matrix.context }}
