name: Validate changes

on:
  push:
    branches-ignore:
      - production

permissions:
  contents: read
  id-token: write

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of terraform files

    strategy:
      matrix:
        context: [ infrastructure, applications ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ${{ matrix.context }}

  validate:
    runs-on: ubuntu-latest
    name: Validate terraform configuration

    strategy:
      matrix:
        context: [ infrastructure, applications ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: ${{ matrix.context }}
