name: Validate changes

on:
  push:
    branches-ignore:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of terraform files
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ARN }}

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: terraform

  validate:
    runs-on: ubuntu-latest
    name: Validate terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ARN }}

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: terraform